<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Proyecto final metodos estadisticos</title>
  <meta name="description" content="Proyecto final metodos estadisticos" />
  <meta name="generator" content="bookdown 0.47 and GitBook 2.6.7" />

  <meta property="og:title" content="Proyecto final metodos estadisticos" />
  <meta property="og:type" content="book" />
  
  
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Proyecto final metodos estadisticos" />
  
  
  

<meta name="author" content="Jesus Esguerra y Santiago Gomez" />


<meta name="date" content="2026-09-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="01-intro.html"><a href="#intro"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="01-intro.html"><a href="#analisis-exploratorio-de-los-datos"><i class="fa fa-check"></i><b>1.1</b> Analisis Exploratorio de los datos</a></li>
<li class="chapter" data-level="1.2" data-path="01-intro.html"><a href="#an%C3%A1lisis-exploratorio-de-price-target"><i class="fa fa-check"></i><b>1.2</b> Análisis exploratorio de price (Target)</a></li>
<li class="chapter" data-level="1.3" data-path="01-intro.html"><a href="#an%C3%A1lisis-de-las-variables-num%C3%A9ricas-independientes"><i class="fa fa-check"></i><b>1.3</b> Análisis de las variables numéricas independientes</a></li>
<li class="chapter" data-level="1.4" data-path="01-intro.html"><a href="#an%C3%A1lisis-de-variable-categ%C3%B3rica-body-style"><i class="fa fa-check"></i><b>1.4</b> Análisis de variable categórica: body-style</a></li>
<li class="chapter" data-level="1.5" data-path="01-intro.html"><a href="#an%C3%A1lisis-exploratorio-bivariado"><i class="fa fa-check"></i><b>1.5</b> Análisis Exploratorio Bivariado</a></li>
<li class="chapter" data-level="1.6" data-path="01-intro.html"><a href="#feature-engineering-nuevas-variables"><i class="fa fa-check"></i><b>1.6</b> Feature Engineering (Nuevas Variables)</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Proyecto final metodos estadisticos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">Proyecto final metodos estadisticos</h1>
<p class="author"><em>Jesus Esguerra y Santiago Gomez</em></p>
<p class="date"><em>2026-09-17</em></p>
</div>
<div id="intro" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Chapter 1</span> Introducción<a href="#intro" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Para este trabajo vamos a utilizar el conocido conjunto de datos Automobile (obtenido del 1985 Ward’s Automotive Yearbook de la UCI). Este dataset incluye información muy variada sobre diferentes modelos de autos de esa época.</p>
<p>En total, la base de datos cuenta con 205 observaciones (autos) y 25 variables que mezclan datos numéricos y categóricos. La información se divide principalmente en tres aspectos:</p>
<p><strong>Características técnicas y físicas:</strong> Detalles del vehículo como las dimensiones, el tipo de motor, los caballos de fuerza (horsepower) y el rendimiento de combustible.</p>
<p><strong>Nivel de riesgo (Symboling):</strong> Una puntuación asignada por aseguradoras que va desde +3 (autos considerados más riesgosos o deportivos) hasta -3 (autos muy seguros).</p>
<p><strong>Pérdidas normalizadas:</strong> Un indicador que mide el pago promedio de siniestros por año, ajustado según el tamaño y tipo de auto.</p>
<p><strong>Objetivo del Trabajo</strong>
El propósito principal de este análisis será limpiar y preparar los datos para construir un modelo predictivo donde nuestra variable objetivo (o variable dependiente) será el precio <code>price</code>. La idea es descubrir qué características técnicas y comerciales influyen más en el valor de mercado de los automóviles.</p>
<div id="analisis-exploratorio-de-los-datos" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Analisis Exploratorio de los datos<a href="#analisis-exploratorio-de-los-datos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Librerias ultilizadas:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(dtplyr)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(Amelia)</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb1-7"><a href="#cb1-7" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-8"><a href="#cb1-8" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-9"><a href="#cb1-9" tabindex="-1"></a><span class="fu">library</span>(moments) </span>
<span id="cb1-10"><a href="#cb1-10" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-11"><a href="#cb1-11" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-12"><a href="#cb1-12" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a>Automobile <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">&quot;data/automobile/imports-85.data&quot;</span>, </span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a>    <span class="at">col_names =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Rows: 205 Columns: 26
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## chr (16): X2, X3, X4, X5, X6, X7, X8, X9, X15, X16, X18, X19, X20, X22, X23,...
## dbl (10): X1, X10, X11, X12, X13, X14, X17, X21, X24, X25
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="fu">colnames</span>(Automobile) <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a>  <span class="st">&quot;symboling&quot;</span>, <span class="st">&quot;normalized-losses&quot;</span>, <span class="st">&quot;make&quot;</span>, <span class="st">&quot;fuel-type&quot;</span>, <span class="st">&quot;aspiration&quot;</span>,</span>
<span id="cb4-3"><a href="#cb4-3" tabindex="-1"></a>  <span class="st">&quot;num-of-doors&quot;</span>, <span class="st">&quot;body-style&quot;</span>, <span class="st">&quot;drive-wheels&quot;</span>, <span class="st">&quot;engine-location&quot;</span>,</span>
<span id="cb4-4"><a href="#cb4-4" tabindex="-1"></a>  <span class="st">&quot;wheel-base&quot;</span>, <span class="st">&quot;length&quot;</span>, <span class="st">&quot;width&quot;</span>, <span class="st">&quot;height&quot;</span>, <span class="st">&quot;curb-weight&quot;</span>,</span>
<span id="cb4-5"><a href="#cb4-5" tabindex="-1"></a>  <span class="st">&quot;engine-type&quot;</span>, <span class="st">&quot;num-of-cylinders&quot;</span>, <span class="st">&quot;engine-size&quot;</span>, <span class="st">&quot;fuel-system&quot;</span>,</span>
<span id="cb4-6"><a href="#cb4-6" tabindex="-1"></a>  <span class="st">&quot;bore&quot;</span>, <span class="st">&quot;stroke&quot;</span>, <span class="st">&quot;compression-ratio&quot;</span>, <span class="st">&quot;horsepower&quot;</span>, <span class="st">&quot;peak-rpm&quot;</span>,</span>
<span id="cb4-7"><a href="#cb4-7" tabindex="-1"></a>  <span class="st">&quot;city-mpg&quot;</span>, <span class="st">&quot;highway-mpg&quot;</span>, <span class="st">&quot;price&quot;</span></span>
<span id="cb4-8"><a href="#cb4-8" tabindex="-1"></a>)</span></code></pre></div>
<p>Veamos las primeras 5 filas</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a><span class="fu">kable</span>(<span class="fu">head</span>(Automobile, <span class="at">n=</span><span class="dv">5</span>), <span class="at">caption=</span><span class="st">&quot;Primeras 5 observaciones de la base de datos Automobile&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" tabindex="-1"></a>  <span class="fu">scroll_box</span>(<span class="at">width=</span><span class="st">&quot;100%&quot;</span>, <span class="at">height =</span> <span class="st">&quot;300px&quot;</span>)</span></code></pre></div>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:300px; overflow-x: scroll; width:100%; ">
<table>
<caption>
<span id="tab:filas">Table 1.1: </span><span id="tab:filas">Table 1.2: </span>Primeras 5 observaciones de la base de datos Automobile
</caption>
<thead>
<tr>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
symboling
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
normalized-losses
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
make
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
fuel-type
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
aspiration
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
num-of-doors
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
body-style
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
drive-wheels
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
engine-location
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
wheel-base
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
length
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
width
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
height
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
curb-weight
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
engine-type
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
num-of-cylinders
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
engine-size
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
fuel-system
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
bore
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
stroke
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
compression-ratio
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
horsepower
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
peak-rpm
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
city-mpg
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
highway-mpg
</th>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
price
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
?
</td>
<td style="text-align:left;">
alfa-romero
</td>
<td style="text-align:left;">
gas
</td>
<td style="text-align:left;">
std
</td>
<td style="text-align:left;">
two
</td>
<td style="text-align:left;">
convertible
</td>
<td style="text-align:left;">
rwd
</td>
<td style="text-align:left;">
front
</td>
<td style="text-align:right;">
88.6
</td>
<td style="text-align:right;">
168.8
</td>
<td style="text-align:right;">
64.1
</td>
<td style="text-align:right;">
48.8
</td>
<td style="text-align:right;">
2548
</td>
<td style="text-align:left;">
dohc
</td>
<td style="text-align:left;">
four
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:left;">
mpfi
</td>
<td style="text-align:left;">
3.47
</td>
<td style="text-align:left;">
2.68
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:left;">
111
</td>
<td style="text-align:left;">
5000
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:left;">
13495
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:left;">
?
</td>
<td style="text-align:left;">
alfa-romero
</td>
<td style="text-align:left;">
gas
</td>
<td style="text-align:left;">
std
</td>
<td style="text-align:left;">
two
</td>
<td style="text-align:left;">
convertible
</td>
<td style="text-align:left;">
rwd
</td>
<td style="text-align:left;">
front
</td>
<td style="text-align:right;">
88.6
</td>
<td style="text-align:right;">
168.8
</td>
<td style="text-align:right;">
64.1
</td>
<td style="text-align:right;">
48.8
</td>
<td style="text-align:right;">
2548
</td>
<td style="text-align:left;">
dohc
</td>
<td style="text-align:left;">
four
</td>
<td style="text-align:right;">
130
</td>
<td style="text-align:left;">
mpfi
</td>
<td style="text-align:left;">
3.47
</td>
<td style="text-align:left;">
2.68
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:left;">
111
</td>
<td style="text-align:left;">
5000
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:left;">
16500
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:left;">
?
</td>
<td style="text-align:left;">
alfa-romero
</td>
<td style="text-align:left;">
gas
</td>
<td style="text-align:left;">
std
</td>
<td style="text-align:left;">
two
</td>
<td style="text-align:left;">
hatchback
</td>
<td style="text-align:left;">
rwd
</td>
<td style="text-align:left;">
front
</td>
<td style="text-align:right;">
94.5
</td>
<td style="text-align:right;">
171.2
</td>
<td style="text-align:right;">
65.5
</td>
<td style="text-align:right;">
52.4
</td>
<td style="text-align:right;">
2823
</td>
<td style="text-align:left;">
ohcv
</td>
<td style="text-align:left;">
six
</td>
<td style="text-align:right;">
152
</td>
<td style="text-align:left;">
mpfi
</td>
<td style="text-align:left;">
2.68
</td>
<td style="text-align:left;">
3.47
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:left;">
154
</td>
<td style="text-align:left;">
5000
</td>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:left;">
16500
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
164
</td>
<td style="text-align:left;">
audi
</td>
<td style="text-align:left;">
gas
</td>
<td style="text-align:left;">
std
</td>
<td style="text-align:left;">
four
</td>
<td style="text-align:left;">
sedan
</td>
<td style="text-align:left;">
fwd
</td>
<td style="text-align:left;">
front
</td>
<td style="text-align:right;">
99.8
</td>
<td style="text-align:right;">
176.6
</td>
<td style="text-align:right;">
66.2
</td>
<td style="text-align:right;">
54.3
</td>
<td style="text-align:right;">
2337
</td>
<td style="text-align:left;">
ohc
</td>
<td style="text-align:left;">
four
</td>
<td style="text-align:right;">
109
</td>
<td style="text-align:left;">
mpfi
</td>
<td style="text-align:left;">
3.19
</td>
<td style="text-align:left;">
3.40
</td>
<td style="text-align:right;">
10
</td>
<td style="text-align:left;">
102
</td>
<td style="text-align:left;">
5500
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
30
</td>
<td style="text-align:left;">
13950
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:left;">
164
</td>
<td style="text-align:left;">
audi
</td>
<td style="text-align:left;">
gas
</td>
<td style="text-align:left;">
std
</td>
<td style="text-align:left;">
four
</td>
<td style="text-align:left;">
sedan
</td>
<td style="text-align:left;">
4wd
</td>
<td style="text-align:left;">
front
</td>
<td style="text-align:right;">
99.4
</td>
<td style="text-align:right;">
176.6
</td>
<td style="text-align:right;">
66.4
</td>
<td style="text-align:right;">
54.3
</td>
<td style="text-align:right;">
2824
</td>
<td style="text-align:left;">
ohc
</td>
<td style="text-align:left;">
five
</td>
<td style="text-align:right;">
136
</td>
<td style="text-align:left;">
mpfi
</td>
<td style="text-align:left;">
3.19
</td>
<td style="text-align:left;">
3.40
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:left;">
115
</td>
<td style="text-align:left;">
5500
</td>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
22
</td>
<td style="text-align:left;">
17450
</td>
</tr>
</tbody>
</table>
</div>
<p>La estructura de los datos</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="fu">str</span>(Automobile)</span></code></pre></div>
<pre><code>## spc_tbl_ [205 × 26] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
##  $ symboling        : num [1:205] 3 3 1 2 2 2 1 1 1 0 ...
##  $ normalized-losses: chr [1:205] &quot;?&quot; &quot;?&quot; &quot;?&quot; &quot;164&quot; ...
##  $ make             : chr [1:205] &quot;alfa-romero&quot; &quot;alfa-romero&quot; &quot;alfa-romero&quot; &quot;audi&quot; ...
##  $ fuel-type        : chr [1:205] &quot;gas&quot; &quot;gas&quot; &quot;gas&quot; &quot;gas&quot; ...
##  $ aspiration       : chr [1:205] &quot;std&quot; &quot;std&quot; &quot;std&quot; &quot;std&quot; ...
##  $ num-of-doors     : chr [1:205] &quot;two&quot; &quot;two&quot; &quot;two&quot; &quot;four&quot; ...
##  $ body-style       : chr [1:205] &quot;convertible&quot; &quot;convertible&quot; &quot;hatchback&quot; &quot;sedan&quot; ...
##  $ drive-wheels     : chr [1:205] &quot;rwd&quot; &quot;rwd&quot; &quot;rwd&quot; &quot;fwd&quot; ...
##  $ engine-location  : chr [1:205] &quot;front&quot; &quot;front&quot; &quot;front&quot; &quot;front&quot; ...
##  $ wheel-base       : num [1:205] 88.6 88.6 94.5 99.8 99.4 ...
##  $ length           : num [1:205] 169 169 171 177 177 ...
##  $ width            : num [1:205] 64.1 64.1 65.5 66.2 66.4 66.3 71.4 71.4 71.4 67.9 ...
##  $ height           : num [1:205] 48.8 48.8 52.4 54.3 54.3 53.1 55.7 55.7 55.9 52 ...
##  $ curb-weight      : num [1:205] 2548 2548 2823 2337 2824 ...
##  $ engine-type      : chr [1:205] &quot;dohc&quot; &quot;dohc&quot; &quot;ohcv&quot; &quot;ohc&quot; ...
##  $ num-of-cylinders : chr [1:205] &quot;four&quot; &quot;four&quot; &quot;six&quot; &quot;four&quot; ...
##  $ engine-size      : num [1:205] 130 130 152 109 136 136 136 136 131 131 ...
##  $ fuel-system      : chr [1:205] &quot;mpfi&quot; &quot;mpfi&quot; &quot;mpfi&quot; &quot;mpfi&quot; ...
##  $ bore             : chr [1:205] &quot;3.47&quot; &quot;3.47&quot; &quot;2.68&quot; &quot;3.19&quot; ...
##  $ stroke           : chr [1:205] &quot;2.68&quot; &quot;2.68&quot; &quot;3.47&quot; &quot;3.40&quot; ...
##  $ compression-ratio: num [1:205] 9 9 9 10 8 8.5 8.5 8.5 8.3 7 ...
##  $ horsepower       : chr [1:205] &quot;111&quot; &quot;111&quot; &quot;154&quot; &quot;102&quot; ...
##  $ peak-rpm         : chr [1:205] &quot;5000&quot; &quot;5000&quot; &quot;5000&quot; &quot;5500&quot; ...
##  $ city-mpg         : num [1:205] 21 21 19 24 18 19 19 19 17 16 ...
##  $ highway-mpg      : num [1:205] 27 27 26 30 22 25 25 25 20 22 ...
##  $ price            : chr [1:205] &quot;13495&quot; &quot;16500&quot; &quot;16500&quot; &quot;13950&quot; ...
##  - attr(*, &quot;spec&quot;)=
##   .. cols(
##   ..   X1 = col_double(),
##   ..   X2 = col_character(),
##   ..   X3 = col_character(),
##   ..   X4 = col_character(),
##   ..   X5 = col_character(),
##   ..   X6 = col_character(),
##   ..   X7 = col_character(),
##   ..   X8 = col_character(),
##   ..   X9 = col_character(),
##   ..   X10 = col_double(),
##   ..   X11 = col_double(),
##   ..   X12 = col_double(),
##   ..   X13 = col_double(),
##   ..   X14 = col_double(),
##   ..   X15 = col_character(),
##   ..   X16 = col_character(),
##   ..   X17 = col_double(),
##   ..   X18 = col_character(),
##   ..   X19 = col_character(),
##   ..   X20 = col_character(),
##   ..   X21 = col_double(),
##   ..   X22 = col_character(),
##   ..   X23 = col_character(),
##   ..   X24 = col_double(),
##   ..   X25 = col_double(),
##   ..   X26 = col_character()
##   .. )
##  - attr(*, &quot;problems&quot;)=&lt;pointer: 0x000001dc3f9f2b80&gt;</code></pre>
<p>Veamos si hay datos faltantes</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a>colSums</span></code></pre></div>
<pre><code>## function (x, na.rm = FALSE, dims = 1L) 
## {
##     if (is.data.frame(x)) 
##         x &lt;- as.matrix(x)
##     if (!is.array(x) || length(dn &lt;- dim(x)) &lt; 2L) 
##         stop(&quot;&#39;x&#39; must be an array of at least two dimensions&quot;)
##     if (length(dims) != 1L || dims &lt; 1L || dims &gt; length(dn) - 
##         1L) 
##         stop(&quot;invalid &#39;dims&#39;&quot;)
##     n &lt;- prod(dn[id &lt;- seq_len(dims)])
##     dn &lt;- dn[-id]
##     z &lt;- .Internal(colSums(x, n, prod(dn), na.rm))
##     if (length(dn) &gt; 1L) {
##         dim(z) &lt;- dn
##         dimnames(z) &lt;- dimnames(x)[-id]
##     }
##     else names(z) &lt;- dimnames(x)[[dims + 1L]]
##     z
## }
## &lt;bytecode: 0x000001dc41237498&gt;
## &lt;environment: namespace:base&gt;</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a>Automobile[Automobile <span class="sc">==</span> <span class="st">&quot;?&quot;</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a>Automobile <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)),<span class="at">.names =</span> <span class="st">&quot;NA_{.col}&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb10-5"><a href="#cb10-5" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">&quot;Conteo de valores faltantes&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb10-6"><a href="#cb10-6" tabindex="-1"></a>  <span class="fu">scroll_box</span>(<span class="at">width=</span><span class="st">&quot;100%&quot;</span>, <span class="at">height =</span> <span class="st">&quot;300px&quot;</span>)</span></code></pre></div>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:300px; overflow-x: scroll; width:100%; ">
<table>
<caption>
<span id="tab:faltantes">Table 1.3: </span><span id="tab:faltantes">Table 1.4: </span>Conteo de valores faltantes
</caption>
<thead>
<tr>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_symboling
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_normalized-losses
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_make
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_fuel-type
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_aspiration
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_num-of-doors
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_body-style
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_drive-wheels
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_engine-location
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_wheel-base
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_length
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_width
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_height
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_curb-weight
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_engine-type
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_num-of-cylinders
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_engine-size
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_fuel-system
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_bore
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_stroke
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_compression-ratio
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_horsepower
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_peak-rpm
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_city-mpg
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_highway-mpg
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_price
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
</tr>
</tbody>
</table>
</div>
<p>Observamos que un total de 5 variables(<code>normalized-losses</code>, <code>num-of-doors</code>, <code>bore</code>, <code>stroke</code> y <code>price</code>) presentan valores faltantes. Debido a que la variable <code>normalized-losses</code> presenta una cantidad considerable de valores faltantes (42), si optamos por eliminar esas filas, se afectaría negativamente la potencia estadística.</p>
<p>Por lo anterior, hagamos imputación de datos faltantes</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a>moda <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>  ux <span class="ot">&lt;-</span> <span class="fu">unique</span>(<span class="fu">na.omit</span>(x))</span>
<span id="cb11-3"><a href="#cb11-3" tabindex="-1"></a>  ux[<span class="fu">which.max</span>(<span class="fu">tabulate</span>(<span class="fu">match</span>(x, ux)))]</span>
<span id="cb11-4"><a href="#cb11-4" tabindex="-1"></a>}</span>
<span id="cb11-5"><a href="#cb11-5" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" tabindex="-1"></a>Automobile <span class="sc">%&gt;%</span></span>
<span id="cb11-7"><a href="#cb11-7" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.character), <span class="sc">~</span> <span class="fu">na_if</span>(<span class="fu">na_if</span>(., <span class="st">&quot;?&quot;</span>), <span class="st">&quot;&quot;</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb11-8"><a href="#cb11-8" tabindex="-1"></a>  <span class="fu">type.convert</span>(<span class="at">as.is =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-9"><a href="#cb11-9" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(<span class="sc">~</span> <span class="fu">is.character</span>(.) <span class="sc">|</span> <span class="fu">is.factor</span>(.)), <span class="sc">~</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(.), <span class="fu">moda</span>(.), <span class="at">no =</span> <span class="fu">as.character</span>(.)))) <span class="sc">%&gt;%</span> </span>
<span id="cb11-10"><a href="#cb11-10" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), <span class="sc">~</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(.), <span class="fu">mean</span>(., <span class="at">na.rm =</span> <span class="cn">TRUE</span>), .))) <span class="ot">-&gt;</span> df</span></code></pre></div>
<p>Verifiquemos si tiene datos faltantes</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)), <span class="at">.names =</span> <span class="st">&quot;NA_{.col}&quot;</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a>  <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">&quot;Conteo de valores faltantes&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb12-4"><a href="#cb12-4" tabindex="-1"></a>  <span class="fu">scroll_box</span>(<span class="at">width=</span><span class="st">&quot;100%&quot;</span>, <span class="at">height =</span> <span class="st">&quot;300px&quot;</span>)</span></code></pre></div>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:300px; overflow-x: scroll; width:100%; ">
<table>
<caption>
<span id="tab:faltantes2">Table 1.5: </span><span id="tab:faltantes2">Table 1.6: </span>Conteo de valores faltantes
</caption>
<thead>
<tr>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_symboling
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_normalized-losses
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_make
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_fuel-type
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_aspiration
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_num-of-doors
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_body-style
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_drive-wheels
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_engine-location
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_wheel-base
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_length
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_width
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_height
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_curb-weight
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_engine-type
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_num-of-cylinders
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_engine-size
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_fuel-system
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_bore
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_stroke
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_compression-ratio
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_horsepower
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_peak-rpm
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_city-mpg
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_highway-mpg
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
NA_price
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
</div>
<p>Ahora si nuestra muestra ya no presenta valores faltantes</p>
<p>Vamos a convertir la variable ‘fuel-type’ en un factor</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a>df<span class="sc">$</span><span class="st">`</span><span class="at">fuel-type</span><span class="st">`</span> <span class="ot">&lt;-</span> <span class="fu">factor</span>(df<span class="sc">$</span><span class="st">`</span><span class="at">fuel-type</span><span class="st">`</span>)</span></code></pre></div>
</div>
<div id="análisis-exploratorio-de-price-target" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Análisis exploratorio de price (Target)<a href="#an%C3%A1lisis-exploratorio-de-price-target" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Realicemos el resumen estadístico de la variable</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(price),</span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a>                 <span class="at">media=</span> <span class="fu">mean</span>(price, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a>                 <span class="at">sd =</span> <span class="fu">sd</span>(price, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-4"><a href="#cb14-4" tabindex="-1"></a>                 <span class="at">mediana =</span> <span class="fu">median</span>(price, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-5"><a href="#cb14-5" tabindex="-1"></a>                 <span class="at">RIC =</span> <span class="fu">IQR</span>(price, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-6"><a href="#cb14-6" tabindex="-1"></a>                 <span class="at">Q1 =</span> <span class="fu">quantile</span>(price, <span class="fl">0.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-7"><a href="#cb14-7" tabindex="-1"></a>                 <span class="at">Q3 =</span> <span class="fu">quantile</span>(price, <span class="fl">0.75</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-8"><a href="#cb14-8" tabindex="-1"></a>                 <span class="at">minimo =</span> <span class="fu">min</span>(price, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-9"><a href="#cb14-9" tabindex="-1"></a>                 <span class="at">maximo =</span> <span class="fu">max</span>(price, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-10"><a href="#cb14-10" tabindex="-1"></a>                 <span class="at">asimetria =</span> <span class="fu">skewness</span>(price, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-11"><a href="#cb14-11" tabindex="-1"></a>                 <span class="at">curtosis =</span> <span class="fu">kurtosis</span>(price, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb14-12"><a href="#cb14-12" tabindex="-1"></a>    <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">&quot;Resumen estadistico de la variable&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb14-13"><a href="#cb14-13" tabindex="-1"></a>    <span class="fu">scroll_box</span>(<span class="at">width=</span><span class="st">&quot;100%&quot;</span>, <span class="at">height =</span> <span class="st">&quot;300px&quot;</span>)</span></code></pre></div>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:300px; overflow-x: scroll; width:100%; ">
<table>
<caption>
(#tab:stats_price)(#tab:stats_price)Resumen estadistico de la variable
</caption>
<thead>
<tr>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
n
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
media
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
sd
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
mediana
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
RIC
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
Q1
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
Q3
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
minimo
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
maximo
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
asimetria
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
curtosis
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
205
</td>
<td style="text-align:right;">
13207.13
</td>
<td style="text-align:right;">
7868.768
</td>
<td style="text-align:right;">
10595
</td>
<td style="text-align:right;">
8712
</td>
<td style="text-align:right;">
7788
</td>
<td style="text-align:right;">
16500
</td>
<td style="text-align:right;">
5118
</td>
<td style="text-align:right;">
45400
</td>
<td style="text-align:right;">
1.813926
</td>
<td style="text-align:right;">
6.243836
</td>
</tr>
</tbody>
</table>
</div>
<p>El análisis de la variable <code>price</code> a partir de 205 automoviles revela que el precio promedio de los autos se sitúa en torno a los $13207.13 USD (SD=7868.7). La distribución muestra que la mitad de los autos registran valores inferiores o iguales a $10595 USD, mientras que el 50% central se concentra en un rango intercuantílico de $8712 USD(delimitado entre los $7788 y $16500).</p>
<p>Los precios oscilan entre un mínimo de $5118 USD y un máximo de $ 45400 USD, reflejando una marcada dispersión. Adicionalmente, el coeficiente de asimetría obtenido es de 1.8, lo que indica una asimetría positiva fuerte. Esto revela que la gran mayoría de los automóviles de la muestra se concentran en rengos de precios accesibles, mientras que existe un grupo minoritario de vehículos de alta gama cuyos precios elevados estiran la distribución hacia la derecha.</p>
<p>Veamos un Boxplot</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y=</span> <span class="st">&quot;&quot;</span>, <span class="at">x=</span>price))<span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9b5e4f&quot;</span>,<span class="at">color =</span> <span class="st">&quot;#9b324f&quot;</span>,</span>
<span id="cb15-4"><a href="#cb15-4" tabindex="-1"></a>               <span class="at">outlier.color =</span> <span class="st">&#39;#e74c3c&#39;</span>)<span class="sc">+</span></span>
<span id="cb15-5"><a href="#cb15-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun=</span> mean, <span class="at">geom=</span><span class="st">&#39;point&#39;</span>, <span class="at">shape=</span><span class="dv">20</span>,</span>
<span id="cb15-6"><a href="#cb15-6" tabindex="-1"></a>               <span class="at">size=</span><span class="dv">4</span>, <span class="at">color=</span><span class="st">&#39;navy&#39;</span>) <span class="sc">+</span></span>
<span id="cb15-7"><a href="#cb15-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Dispersión y valores atípicos del precio&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Precio&quot;</span>, <span class="at">y =</span> <span class="st">&quot;&quot;</span>) <span class="sc">+</span></span>
<span id="cb15-8"><a href="#cb15-8" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/histprice-1.png" alt="" width="672" /></p>
<p>Ahora un histograma</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> price)) <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y=</span><span class="fu">after_stat</span>(density)),</span>
<span id="cb16-4"><a href="#cb16-4" tabindex="-1"></a>                 <span class="at">binwidth =</span> <span class="dv">2500</span>,</span>
<span id="cb16-5"><a href="#cb16-5" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">&quot;#9b5e4f&quot;</span>,</span>
<span id="cb16-6"><a href="#cb16-6" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">&quot;white&quot;</span>,</span>
<span id="cb16-7"><a href="#cb16-7" tabindex="-1"></a>                 <span class="at">alpha =</span> <span class="fl">0.7</span>)<span class="sc">+</span></span>
<span id="cb16-8"><a href="#cb16-8" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color=</span><span class="st">&quot;brown&quot;</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>)<span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span> <span class="st">&#39;Distribución del precio de los automóviles&#39;</span>,</span>
<span id="cb16-10"><a href="#cb16-10" tabindex="-1"></a>       <span class="at">x=</span><span class="st">&#39;Precio (USD)&#39;</span>,</span>
<span id="cb16-11"><a href="#cb16-11" tabindex="-1"></a>       <span class="at">y =</span><span class="st">&#39;Densidad&#39;</span>)<span class="sc">+</span></span>
<span id="cb16-12"><a href="#cb16-12" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-2-1.png" alt="" width="672" /></p>
<p>El análisis de <code>price</code> muestra una distribución con sesgo positivo, donde predominan los autos con precios económicos y medios frente a un grupo reducido de vehículos alta gama. A través de la visualización gráfica se identifican valores atípicos superiores que superan los <strong>$30000 USD</strong>. Esta condición genera una diferencia notable entre la media y la mediana que afectará el comportamiento de los algoritmos predictivoss, haciendo necesario gestionar este detalle durante las siguientes etapas del análisis.</p>
</div>
<div id="análisis-de-las-variables-numéricas-independientes" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Análisis de las variables numéricas independientes<a href="#an%C3%A1lisis-de-las-variables-num%C3%A9ricas-independientes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Analizaremos inicialmente las variables numéricas</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a>  <span class="fu">select</span>(<span class="st">`</span><span class="at">engine-size</span><span class="st">`</span>, horsepower, <span class="st">`</span><span class="at">city-mpg</span><span class="st">`</span>, <span class="st">`</span><span class="at">curb-weight</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb17-4"><a href="#cb17-4" tabindex="-1"></a>    <span class="at">cols=</span><span class="fu">everything</span>(),</span>
<span id="cb17-5"><a href="#cb17-5" tabindex="-1"></a>    <span class="at">names_to=</span> <span class="st">&#39;variable&#39;</span>,</span>
<span id="cb17-6"><a href="#cb17-6" tabindex="-1"></a>    <span class="at">values_to=</span> <span class="st">&#39;valor&#39;</span></span>
<span id="cb17-7"><a href="#cb17-7" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb17-8"><a href="#cb17-8" tabindex="-1"></a>  <span class="fu">group_by</span>(variable) <span class="sc">%&gt;%</span></span>
<span id="cb17-9"><a href="#cb17-9" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(valor),</span>
<span id="cb17-10"><a href="#cb17-10" tabindex="-1"></a>                 <span class="at">media=</span> <span class="fu">mean</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb17-11"><a href="#cb17-11" tabindex="-1"></a>                 <span class="at">sd =</span> <span class="fu">sd</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb17-12"><a href="#cb17-12" tabindex="-1"></a>                 <span class="at">mediana =</span> <span class="fu">median</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb17-13"><a href="#cb17-13" tabindex="-1"></a>                 <span class="at">RIC =</span> <span class="fu">IQR</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb17-14"><a href="#cb17-14" tabindex="-1"></a>                 <span class="at">minimo =</span> <span class="fu">min</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb17-15"><a href="#cb17-15" tabindex="-1"></a>                 <span class="at">maximo =</span> <span class="fu">max</span>(valor, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))<span class="sc">%&gt;%</span> </span>
<span id="cb17-16"><a href="#cb17-16" tabindex="-1"></a>    <span class="fu">kable</span>(<span class="at">caption =</span> <span class="st">&quot;Resumen estadistico de la variables numéricas independientes&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-17"><a href="#cb17-17" tabindex="-1"></a>    <span class="fu">scroll_box</span>(<span class="at">width=</span><span class="st">&quot;100%&quot;</span>, <span class="at">height =</span> <span class="st">&quot;300px&quot;</span>)</span></code></pre></div>
<div style="border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:300px; overflow-x: scroll; width:100%; ">
<table>
<caption>
(#tab:var_indep_num)(#tab:var_indep_num)Resumen estadistico de la variables numéricas independientes
</caption>
<thead>
<tr>
<th style="text-align:left;position: sticky; top:0; background-color: #FFFFFF;">
variable
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
n
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
media
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
sd
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
mediana
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
RIC
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
minimo
</th>
<th style="text-align:right;position: sticky; top:0; background-color: #FFFFFF;">
maximo
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
city-mpg
</td>
<td style="text-align:right;">
205
</td>
<td style="text-align:right;">
25.21951
</td>
<td style="text-align:right;">
6.542142
</td>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
49
</td>
</tr>
<tr>
<td style="text-align:left;">
curb-weight
</td>
<td style="text-align:right;">
205
</td>
<td style="text-align:right;">
2555.56585
</td>
<td style="text-align:right;">
520.680203
</td>
<td style="text-align:right;">
2414
</td>
<td style="text-align:right;">
790
</td>
<td style="text-align:right;">
1488
</td>
<td style="text-align:right;">
4066
</td>
</tr>
<tr>
<td style="text-align:left;">
engine-size
</td>
<td style="text-align:right;">
205
</td>
<td style="text-align:right;">
126.90732
</td>
<td style="text-align:right;">
41.642693
</td>
<td style="text-align:right;">
120
</td>
<td style="text-align:right;">
44
</td>
<td style="text-align:right;">
61
</td>
<td style="text-align:right;">
326
</td>
</tr>
<tr>
<td style="text-align:left;">
horsepower
</td>
<td style="text-align:right;">
205
</td>
<td style="text-align:right;">
104.25616
</td>
<td style="text-align:right;">
39.519211
</td>
<td style="text-align:right;">
95
</td>
<td style="text-align:right;">
46
</td>
<td style="text-align:right;">
48
</td>
<td style="text-align:right;">
288
</td>
</tr>
</tbody>
</table>
</div>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb18-2"><a href="#cb18-2" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y=</span> <span class="st">&quot;&quot;</span>, <span class="at">x=</span><span class="st">`</span><span class="at">engine-size</span><span class="st">`</span>))<span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9b5e4f&quot;</span>,<span class="at">color =</span> <span class="st">&quot;brown&quot;</span>, <span class="at">outlier.color =</span> <span class="st">&#39;#2980b9&#39;</span>)<span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Tamaño del Motor&quot;</span>, <span class="at">y =</span> <span class="st">&quot;&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Cilindrada&quot;</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>()</span>
<span id="cb18-5"><a href="#cb18-5" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb18-7"><a href="#cb18-7" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y=</span> <span class="st">&quot;&quot;</span>, <span class="at">x=</span>horsepower))<span class="sc">+</span></span>
<span id="cb18-8"><a href="#cb18-8" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9b5e4f&quot;</span>,<span class="at">color =</span> <span class="st">&quot;brown&quot;</span>, <span class="at">outlier.color =</span> <span class="st">&#39;#2980b9&#39;</span>)<span class="sc">+</span></span>
<span id="cb18-9"><a href="#cb18-9" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Caballos de Fuerza&quot;</span>, <span class="at">y =</span> <span class="st">&quot;&quot;</span>, <span class="at">x =</span> <span class="st">&quot;HP&quot;</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>()</span>
<span id="cb18-10"><a href="#cb18-10" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb18-12"><a href="#cb18-12" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y=</span> <span class="st">&quot;&quot;</span>, <span class="at">x=</span><span class="st">`</span><span class="at">city-mpg</span><span class="st">`</span>))<span class="sc">+</span></span>
<span id="cb18-13"><a href="#cb18-13" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9b5e4f&quot;</span>,<span class="at">color =</span> <span class="st">&quot;brown&quot;</span>, <span class="at">outlier.color =</span> <span class="st">&#39;#2980b9&#39;</span>)<span class="sc">+</span></span>
<span id="cb18-14"><a href="#cb18-14" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Rendimiento en Ciudad&quot;</span>, <span class="at">y =</span> <span class="st">&quot;&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Millas por Galón&quot;</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>()</span>
<span id="cb18-15"><a href="#cb18-15" tabindex="-1"></a></span>
<span id="cb18-16"><a href="#cb18-16" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb18-17"><a href="#cb18-17" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">y=</span> <span class="st">&quot;&quot;</span>, <span class="at">x=</span><span class="st">`</span><span class="at">curb-weight</span><span class="st">`</span>))<span class="sc">+</span></span>
<span id="cb18-18"><a href="#cb18-18" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9b5e4f&quot;</span>,<span class="at">color =</span> <span class="st">&quot;brown&quot;</span>, <span class="at">outlier.color =</span> <span class="st">&#39;#2980b9&#39;</span>)<span class="sc">+</span></span>
<span id="cb18-19"><a href="#cb18-19" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Peso del Vehículo&quot;</span>, <span class="at">y =</span> <span class="st">&quot;&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Libras&quot;</span>) <span class="sc">+</span> <span class="fu">theme_bw</span>()</span>
<span id="cb18-20"><a href="#cb18-20" tabindex="-1"></a></span>
<span id="cb18-21"><a href="#cb18-21" tabindex="-1"></a>p1 <span class="sc">+</span> p2 <span class="sc">+</span> p3 <span class="sc">+</span> p4</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-3-1.png" alt="" width="672" /></p>
<p>El análisis exploratorio de las principales características mecánicas y de rendimiento de los 205 automóviles muestra los siguientes comportamientos:</p>
<p><strong>Rendimiento en ciudad <code>city-mpg</code>:</strong> Los vehículos presentan un promedio de 25.22 MPG (desviación estándar de 6.54) y una mediana de 24 MPG, con un rango intercuartílico (RIC) de 11. Los valores oscilan entre un mínimo de 13 MPG y un máximo de 49 MPG, reflejando una variabilidad moderada en la eficiencia del combustible, donde la mayoría de los autos se concentran en consumos eficientes o moderados.</p>
<p><strong>Peso del vehículo <code>(curb-weight)</code>:</strong> El peso promedio se sitúa en 2555.57 lbs (SD = 520.68), con una mediana de 2414 lbs y un RIC de 790. La dispersión abarca desde un mínimo de 1488 lbs hasta un máximo de 4066 lbs, lo que evidencia la coexistencia de automóviles ligeros y vehículos de gran carrocería en la muestra.</p>
<p><strong>Tamaño del motor <code>(engine-size)</code>:</strong> Esta variable registra una media de 126.91 pulgadas cúbicas (SD = 41.64) y una mediana de 120, con un RIC de 44. Los valores van desde un mínimo de 61 hasta un máximo de 326, indicando una asimetría positiva impulsada por una minoría de motores de alta cilindrada.</p>
<p><strong>Caballos de fuerza <code>(horsepower)</code>:</strong> La potencia media de los motores es de 104.26 HP (SD = 39.52), con una mediana de 95 HP y un RIC de 46. El rango va desde los 48 HP hasta los 288 HP, mostrando una concentración de vehículos con potencias estándar y un grupo selecto de autos deportivos o de alto rendimiento que extienden la cola de la distribución hacia valores superiores.</p>
</div>
<div id="análisis-de-variable-categórica-body-style" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> Análisis de variable categórica: body-style<a href="#an%C3%A1lisis-de-variable-categ%C3%B3rica-body-style" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" tabindex="-1"></a>tabla_body <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" tabindex="-1"></a>  <span class="fu">count</span>(<span class="st">`</span><span class="at">body-style</span><span class="st">`</span>, <span class="at">name =</span> <span class="st">&quot;n&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>((n <span class="sc">/</span> <span class="fu">sum</span>(n))<span class="sc">*</span><span class="dv">100</span>,<span class="dv">1</span>),</span>
<span id="cb19-4"><a href="#cb19-4" tabindex="-1"></a>         <span class="at">Etiqueta =</span> <span class="fu">paste0</span>(n,<span class="st">&quot; (&quot;</span>,Porcentaje,<span class="st">&quot;%)&quot;</span>))</span>
<span id="cb19-5"><a href="#cb19-5" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" tabindex="-1"></a>tabla_body <span class="sc">%&gt;%</span></span>
<span id="cb19-7"><a href="#cb19-7" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span> <span class="fu">reorder</span>(<span class="st">`</span><span class="at">body-style</span><span class="st">`</span>, <span class="sc">-</span>n), <span class="at">y=</span>n))<span class="sc">+</span></span>
<span id="cb19-8"><a href="#cb19-8" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill=</span> <span class="st">&quot;#9b5e4f&quot;</span>, <span class="at">width=</span><span class="fl">0.6</span>)<span class="sc">+</span></span>
<span id="cb19-9"><a href="#cb19-9" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span> Etiqueta), <span class="at">vjust=</span><span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size=</span><span class="dv">4</span>)<span class="sc">+</span></span>
<span id="cb19-10"><a href="#cb19-10" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribución por Tipo de Carrocería&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Estilo de Carrocería&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Cantidad&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-11"><a href="#cb19-11" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="fl">0.15</span>)))<span class="sc">+</span></span>
<span id="cb19-12"><a href="#cb19-12" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/var_categorica-1.png" alt="" width="672" /></p>
<p>La variable <code>body-style</code> presenta una distribución desigual entre sus categorías. La categoría <code>sedan</code> concentra el 46.8% de los registros, seguida de <code>hatchback</code> con el 34.1%, por lo que en conjunto ambas representan el 80.9% de las observaciones. Las categorías <code>wagon</code>, <code>hardtop</code> y <code>convertible</code> corresponden al 12.2%, 3.9% y 2.9%, respectivamente, evidenciando una baja frecuencia en los diseños minoritarios. Esta distribución evidencia un desbalance entre las categorías, especialmente en el caso de los estilos con menor representación, cuya baja frecuencia puede dificultar la estimación confiable en los modelos estadísticos. En consecuencia, durante el proceso de modelamiento será necesario considerar este desbalance, ya sea mediante técnicas de codificación adecuadas, agrupación de categorías poco representadas o evaluando el impacto de estas en el desempeño de los modelos.</p>
</div>
<div id="análisis-exploratorio-bivariado" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> Análisis Exploratorio Bivariado<a href="#an%C3%A1lisis-exploratorio-bivariado" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="#cb20-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="st">`</span><span class="at">engine-size</span><span class="st">`</span>, <span class="at">y=</span>price)) <span class="sc">+</span></span>
<span id="cb20-3"><a href="#cb20-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha=</span><span class="fl">0.6</span>, <span class="at">color=</span><span class="st">&#39;#2980b9&#39;</span>, <span class="at">size=</span><span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb20-4"><a href="#cb20-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#c0392b&quot;</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb20-5"><a href="#cb20-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&#39;Relación entre el tamaño del motor y el precio&#39;</span>,</span>
<span id="cb20-6"><a href="#cb20-6" tabindex="-1"></a>       <span class="at">x=</span><span class="st">&#39;Tamaño del Motor&#39;</span>,</span>
<span id="cb20-7"><a href="#cb20-7" tabindex="-1"></a>       <span class="at">y=</span><span class="st">&#39;Precio (USD)&#39;</span>) <span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="bookdown-demo_files/figure-html/bi_num_vs_target-1.png" alt="" width="672" /></p>
<p>Los puntos presentan una tendencia ascendente claramente definida, indicando que, a medida que aumenta el tamaño del motor de un automóvil, también tiende a incrementarse su precio en USD. La mayor concentración de observaciones se encuentra en tamaños de motor entre 80 y 150 y valores de precio inferiores a $20,000 USD, aunque existe una dispersión considerable para un mismo nivel de cilindrada.</p>
<p>Se observa que la variabilidad del precio de los vehículos aumenta conforme crece el tamaño del motor, lo que sugiere que en los automóviles con motores más grandes y potentes existen rangos de precios más amplios y diversos (típicamente asociados a vehículos de gama alta o deportivos).</p>
<p>En general, la relación entre el tamaño del motor y el precio es positiva y aproximadamente lineal, siendo una de las asociaciones más fuertes del conjunto de datos. Esto sugiere que el tamaño del motor constituye una variable con un alto poder explicativo para predecir el valor de los automóviles y, por tanto, será un predictor fundamental en la construcción de los modelos de regresión.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">`</span><span class="at">body-style</span><span class="st">`</span>, <span class="at">y =</span> price)) <span class="sc">+</span></span>
<span id="cb22-3"><a href="#cb22-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#9b5e4f&quot;</span>, <span class="at">color =</span> <span class="st">&quot;brown&quot;</span>, <span class="at">outlier.color =</span> <span class="st">&#39;#2980b9&#39;</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb22-4"><a href="#cb22-4" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Distribución del Precio según la Carrocería&quot;</span>, <span class="at">x =</span> <span class="st">&quot;Estilo&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Precio (USD)&quot;</span>) <span class="sc">+</span></span>
<span id="cb22-5"><a href="#cb22-5" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-4-1.png" alt="" width="672" /></p>
<p><strong>Categorías de mayor valor (Convertible y Hardtop):</strong> Los estilos convertible y hardtop registran las medianas de precios más elevadas (situadas aproximadamente entre los $17,000 y $20,000 USD) y cajas más amplias, lo que indica una mayor variabilidad y precios considerablemente más altos en el 50% central de la distribución, reflejando su naturaleza de vehículos orientados a nichos exclusivos o de gama alta.</p>
<p><strong>Segmento económico (Hatchback):</strong> En contraste, los modelos hatchback presentan la distribución con los precios más bajos de la muestra, con una mediana cercana a los $9,000 USD y un rango intercuartílico más compacto, lo que denota mayor homogeneidad en este tipo de vehículos utilitarios o económicos.</p>
<p><strong>Segmentos intermedios y valores atípicos (Sedán y Wagon):</strong> Los estilos sedán y wagon muestran medianas similares ubicadas alrededor de los $12,000 USD. No obstante, el segmento de los sedanes destaca por la presencia de múltiples valores atípicos (outliers) en el extremo superior que superan los $40,000 USD, lo que evidencia la existencia de berlinas o sedanes de lujo dentro de una categoría que mayoritariamente concentra autos de precios moderados.</p>
<p>Estos resultados demuestran que el estilo de carrocería ejerce una influencia notable sobre la valuación de los automóviles, aportando información discriminatoria clave que será de gran utilidad como variable predictiva en los modelos de regresion.</p>
</div>
<div id="feature-engineering-nuevas-variables" class="section level2 hasAnchor" number="1.6">
<h2><span class="header-section-number">1.6</span> Feature Engineering (Nuevas Variables)<a href="#feature-engineering-nuevas-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para reducir la correlación y encontrar mejores predictores, crearemos nuevas variables como el promedio de rendimiento de combustible y la relación peso-potencia.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a>df<span class="sc">$</span>avg_mpg <span class="ot">&lt;-</span> (df<span class="sc">$</span><span class="st">`</span><span class="at">city-mpg</span><span class="st">`</span> <span class="sc">+</span> df<span class="sc">$</span><span class="st">`</span><span class="at">highway-mpg</span><span class="st">`</span>) <span class="sc">/</span> <span class="dv">2</span></span>
<span id="cb23-2"><a href="#cb23-2" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" tabindex="-1"></a>df<span class="sc">$</span>weight_power_ratio <span class="ot">&lt;-</span> df<span class="sc">$</span><span class="st">`</span><span class="at">curb-weight</span><span class="st">`</span> <span class="sc">/</span> df<span class="sc">$</span>horsepower</span>
<span id="cb23-4"><a href="#cb23-4" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" tabindex="-1"></a><span class="fu">cor</span>(df[, <span class="fu">c</span>(<span class="st">&quot;price&quot;</span>, <span class="st">&quot;avg_mpg&quot;</span>, <span class="st">&quot;weight_power_ratio&quot;</span>)], <span class="at">use =</span> <span class="st">&quot;complete.obs&quot;</span>)</span></code></pre></div>
<pre><code>##                         price    avg_mpg weight_power_ratio
## price               1.0000000 -0.6842006         -0.4151810
## avg_mpg            -0.6842006  1.0000000          0.6120429
## weight_power_ratio -0.4151810  0.6120429          1.0000000</code></pre>
<p>La matriz de correlación muestra las asociaciones lineales entre el precio de los automóviles (<code>price</code>), el rendimiento promedio de combustible (<code>avg_mpg</code>) y la relación peso-potencia (<code>weight_power_rati</code>). Se observa una correlación negativa moderada-alta entre el precio y el rendimiento de combustible (-0.684), lo que indica que los vehículos más costosos tienden a consumir más combustible (menor eficiencia en MPG), mientras que la relación entre el precio y la relación peso-potencia presenta una asociación negativa más débil (-0.415). Por su parte, <code>avg_mpg</code> y <code>weight_power_ratio</code> muestran una correlación positiva moderada (0.612), evidenciando que estas variables guardan consistencia lógica dentro de las características técnicas de los vehículos de cara a la construcción de los modelos predictivos.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" tabindex="-1"></a><span class="fu">ggpairs</span>(df[, <span class="fu">c</span>(<span class="st">&quot;price&quot;</span>, <span class="st">&quot;horsepower&quot;</span>, <span class="st">&quot;avg_mpg&quot;</span>, <span class="st">&quot;weight_power_ratio&quot;</span>)])</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-5-1.png" alt="" width="672" /></p>
<p>En la relación con la variable objetivo (<code>price</code>), destaca una fuerte correlación positiva con los caballos de fuerza (<code>horsepower</code> con un coeficiente de <span class="math inline">\(0.758\)</span>), indicando que los vehículos con mayor potencia tienden a registrar precios considerablemente más elevados. Por su parte, el rendimiento de combustible (<code>avg_mpg</code>) presenta una asociación inversa fuerte con el precio (<span class="math inline">\(-0.684\)</span>) y con la potencia (<span class="math inline">\(-0.792\)</span>), lo que confirma que los autos más rápidos y costosos son también los menos eficientes en consumo de combustible, aportando variables predictivas altamente significativas para los futuros modelos de regresión.</p>






</div>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/01-intro.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
